openapi: 3.0.0
info:
  title: QTI Assessment Engine API
  version: 1.0.0
  description: API for managing QTI (Question & Test Interoperability) compliant educational content

servers:
  - url: /api
    description: Base API path

paths:
  /assessment-items:
    post:
      summary: Create a new assessment item from QTI XML
      requestBody:
        required: true
        content:
          application/xml:
            schema:
              type: string
      responses:
        '201':
          description: Assessment item created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssessmentItem'
        '400':
          description: Failed to parse or save QTI XML
        '415':
          description: Content-Type must be application/xml or text/xml

    get:
      summary: Search assessment items
      parameters:
        - name: query
          in: query
          schema:
            type: string
          description: Search query for title
        - name: baseType
          in: query
          schema:
            type: string
          description: Filter by base type
      responses:
        '200':
          description: List of assessment items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AssessmentItem'
        '500':
          description: Failed to search assessment items

  /assessment-items/{identifier}:
    get:
      summary: Get an assessment item by identifier
      parameters:
        - name: identifier
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Assessment item details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssessmentItem'
        '404':
          description: Assessment item not found

    put:
      summary: Update an assessment item
      parameters:
        - name: identifier
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/xml:
            schema:
              type: string
      responses:
        '200':
          description: Assessment item updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssessmentItem'
        '404':
          description: Assessment item not found
        '415':
          description: Content-Type must be application/xml or text/xml

    delete:
      summary: Delete an assessment item
      parameters:
        - name: identifier
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Assessment item deleted successfully
        '404':
          description: Assessment item not found

  /assessment-tests:
    post:
      summary: Create a new assessment test from XML
      requestBody:
        required: true
        content:
          application/xml:
            schema:
              type: string
      responses:
        '201':
          description: Assessment test created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssessmentTest'
        '400':
          description: Failed to parse or save XML
        '415':
          description: Content-Type must be application/xml or text/xml

    get:
      summary: Search assessment tests
      parameters:
        - name: query
          in: query
          schema:
            type: string
          description: Search query for title
        - name: navigationMode
          in: query
          schema:
            type: string
            enum: [linear, nonlinear]
        - name: submissionMode
          in: query
          schema:
            type: string
            enum: [individual, simultaneous]
      responses:
        '200':
          description: List of assessment tests
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AssessmentTest'

  /assessment-tests/{identifier}:
    get:
      summary: Get an assessment test by identifier
      parameters:
        - name: identifier
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Assessment test details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssessmentTest'
        '404':
          description: Assessment test not found

    put:
      summary: Update an assessment test
      parameters:
        - name: identifier
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/xml:
            schema:
              type: string
      responses:
        '200':
          description: Assessment test updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssessmentTest'
        '404':
          description: Assessment test not found
        '415':
          description: Content-Type must be application/xml or text/xml

    delete:
      summary: Delete an assessment test
      parameters:
        - name: identifier
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Assessment test deleted successfully
        '404':
          description: Assessment test not found

  /sections:
    post:
      summary: Create a new section
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SectionCreate'
      responses:
        '201':
          description: Section created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Section'
        '400':
          description: Failed to create section

    get:
      summary: Search sections
      parameters:
        - name: query
          in: query
          schema:
            type: string
          description: Search query for title
        - name: assessmentTestId
          in: query
          schema:
            type: string
        - name: parentId
          in: query
          schema:
            type: string
        - name: page
          in: query
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: string
        - name: sort
          in: query
          schema:
            type: string
        - name: order
          in: query
          schema:
            type: string
            enum: [asc, desc]
      responses:
        '200':
          description: List of sections
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Section'

  /sections/{identifier}:
    get:
      summary: Get a section by identifier
      parameters:
        - name: identifier
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Section details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Section'
        '404':
          description: Section not found

    put:
      summary: Update a section
      parameters:
        - name: identifier
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SectionUpdate'
      responses:
        '200':
          description: Section updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Section'
        '404':
          description: Section not found

    delete:
      summary: Delete a section
      parameters:
        - name: identifier
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Section deleted successfully
        '404':
          description: Section not found

  /sections/{identifier}/items:
    post:
      summary: Add an item to a section
      parameters:
        - name: identifier
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SectionItemAdd'
      responses:
        '201':
          description: Item added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SectionItem'
        '404':
          description: Section not found

  /sections/{identifier}/items/{itemId}:
    delete:
      summary: Remove an item from a section
      parameters:
        - name: identifier
          in: path
          required: true
          schema:
            type: string
        - name: itemId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Item removed successfully
        '404':
          description: Section not found

  /sections/{identifier}/items/{itemId}/order:
    put:
      summary: Update item order in a section
      parameters:
        - name: identifier
          in: path
          required: true
          schema:
            type: string
        - name: itemId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                orderIndex:
                  type: integer
      responses:
        '200':
          description: Item order updated successfully
        '404':
          description: Section not found

components:
  schemas:
    AssessmentItem:
      type: object
      properties:
        id:
          type: integer
        identifier:
          type: string
        title:
          type: string
        baseType:
          type: string
          enum: [identifier, boolean, integer, float, string, point, pair, directedPair, duration, file, uri, intOrIdentifier, stringOrIdentifier]
        rawXml:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    AssessmentTest:
      type: object
      properties:
        id:
          type: integer
        identifier:
          type: string
        title:
          type: string
        navigationMode:
          type: string
          enum: [linear, nonlinear]
        submissionMode:
          type: string
          enum: [individual, simultaneous]
        rawXml:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Section:
      type: object
      properties:
        id:
          type: integer
        identifier:
          type: string
        title:
          type: string
        parentId:
          type: integer
          nullable: true
        assessmentTestId:
          type: integer
        sequence:
          type: integer
        itemCount:
          type: integer
        visible:
          type: boolean
        required:
          type: boolean
        fixed:
          type: boolean
        metadata:
          type: object
        rawXml:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    SectionCreate:
      type: object
      required:
        - identifier
        - title
        - assessmentTestId
        - sequence
      properties:
        identifier:
          type: string
        title:
          type: string
        parentId:
          type: integer
        assessmentTestId:
          type: integer
        sequence:
          type: integer
        visible:
          type: boolean
          default: true
        required:
          type: boolean
          default: true
        fixed:
          type: boolean
          default: false
        metadata:
          type: object
        rawXml:
          type: string

    SectionUpdate:
      type: object
      properties:
        title:
          type: string
        parentId:
          type: integer
        sequence:
          type: integer
        visible:
          type: boolean
        required:
          type: boolean
        fixed:
          type: boolean
        metadata:
          type: object
        rawXml:
          type: string

    SectionItem:
      type: object
      properties:
        id:
          type: integer
        sectionId:
          type: integer
        itemId:
          type: integer
        orderIndex:
          type: integer
        required:
          type: boolean
        selected:
          type: boolean
        fixed:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    SectionItemAdd:
      type: object
      required:
        - itemId
        - orderIndex
      properties:
        itemId:
          type: integer
        orderIndex:
          type: integer
        required:
          type: boolean
          default: true
        selected:
          type: boolean
          default: true
        fixed:
          type: boolean
          default: false